# Generated by Django 4.1.7 on 2023-03-20 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatai", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="Answer",
            new_name="answer",
        ),
    ]
