# Generated by Django 4.1.7 on 2023-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatai", "0002_rename_answer_chathistory_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
